### ISSUE TITLE
Voltage Fluctuation 

### ISSUE THREAD

**Issue by darshittimbadiya** [Khaalidi/HLW8032#3]
Thank you for write these library.

I am facing issue regarding AC Voltage fluctuation.
 
Ex. if i measure voltage using actual Energy meter or Voltage Multi-meter it not fluctuating but while i measure voltage using HLW8032 it getting fluctuation like within 5 sec it goes 220V to 225V and suddenly 219V. Means fluctuation rang is +/- 5V.

so what kind of precaution should i take to get steady voltage.

Please Help regarding these.

**Comment by brunohorta82** [comment]
you can get. power ?

**Comment by Khaalidi** [comment]
Which board are you using?

**Comment by avanceesoftware** [comment]
Esp8266 Wemos D1

**Comment by brunohorta82** [comment]
Esp8266 Wemos D1

**Comment by Khaalidi** [comment]
Which HLW8032 board are you using? I've tested with the HLW8032 board from Electrodragon and my custom board which has an HLW8032. I don't see any fluctuation. I assume the issue maybe because of the configuration chosen on the board you use.  Verify the resistors connected to VP and make changes in the library if it's different.

**Comment by Khaalidi** [comment]
> Thank you for write these library.
> 
> I am facing issue regarding AC Voltage fluctuation.
> 
> Ex. if i measure voltage using actual Energy meter or Voltage Multi-meter it not fluctuating but while i measure voltage using HLW8032 it getting fluctuation like within 5 sec it goes 220V to 225V and suddenly 219V. Means fluctuation rang is +/- 5V.
> 
> so what kind of precaution should i take to get steady voltage.
> 
> Please Help regarding these.

Which HLW8032 board are you using? I've tested with the HLW8032 board from Electrodragon and my custom board which has an HLW8032. I don't see any fluctuation. I assume the issue maybe because of the configuration chosen on the board you use.  Verify the resistors connected to VP and make changes in the library if it's different.
